### ISSUE TITLE
Brakujące uprawnienia?

### ISSUE THREAD

**Issue by sigrond** [Antyradek/pinpolice#1]
W emulatorze w trybie debug aplikacja poprosiła o pozwolenie na używanie kamery, dostała je, a potem się zamknęła.
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pl.antyradek.pinpolice, PID: 7007
    java.lang.RuntimeException: Unable to create service pl.antyradek.pinpolice.CameraService: java.lang.SecurityException: Permission Denial: startForeground from pid=7007, uid=10086 requires android.permission.FOREGROUND_SERVICE
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=7007, uid=10086 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1942)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5198)
        at android.app.Service.startForeground(Service.java:695)
        at pl.antyradek.pinpolice.CameraService.onCreate(CameraService.java:71)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9189)
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1189)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:870)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:20437)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:976)`

**Comment by Antyradek** [comment]
Chyba wiem, o co chodzi. Bardziej mnie zastanawia, że moja wyższa wersja systemu Oreo zezwoliła na uruchomienie bez zezwolenia. Zdaje się, że także budowałem jako target na Pie.
https://developer.android.com/guide/components/services#Foreground
Dodałem linijkę do manifestu. Masz także uprawienia do pushowania.

**Comment by Antyradek** [comment]
Zamknij problem, jeśli zadziała ci na twoim telefonie/emulatorze.
Na emulatorze odpalasz Pie? Może dlatego wyszedł problem.

**Comment by sigrond** [comment]
Teraz leci chyba inny błąd
`I/InstantRun: starting instant run server: is main process
W/radek.pinpolic: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
D/OpenGLRenderer: HWUI GL Pipeline
D/: HostConnection::get() New Host Connection established 0xcc5e8380, tid 8032
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0xdebdcfc0: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xdebdcfc0: ver 2 0 (tinfo 0xdd16f310)
D/EGL_emulation: eglMakeCurrent: 0xdebdcfc0: ver 2 0 (tinfo 0xdd16f310)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pl.antyradek.pinpolice, PID: 7992
    java.lang.RuntimeException: Unable to create service pl.antyradek.pinpolice.CameraService: java.lang.RuntimeException: setParameters failed
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2102)
        at pl.antyradek.pinpolice.CameraService.onCreate(CameraService.java:77)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `
Android na emulatorze jest w wersji 9.

**Comment by Antyradek** [comment]
Z jakiegoś powodu ustawiona na sztywno wielkość obrazu jest wspierana na moim telefonie, a nie na emulatorze. Zrobiłem że będzie brał którąkolwiek większą, niż minimalna, ale może trzeba było by to ustawić na najbliższą wspieraną do zapisanej wielkości.
