### ISSUE TITLE
Wybór frameworka sieci neuronowych

### ISSUE THREAD

**Issue by sigrond** [Antyradek/pinpolice#2]
Udało mi się z Matlaba wyeksportować sieć w formacie ONNX.
https://github.com/onnx/tutorials
Potrzebujemy szybko wybrać jak na androidzie będziemy wołać sieć neuronową.
Caffe2:
- wymaga windows 10
TensorFlow:
- ?

Ewentualnie takie coś:
https://www.mathworks.com/hardware-support/android-programming-simulink.html

**Comment by sigrond** [comment]
przy próbie konwersji z ONNX do TensorFlow:

`(venv) E:\Moje dokumenty\WPAM>onnx-tf convert -t tf -i pinpoliceresnet50.onnx -o
 pinpoliceresnet50.pb

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-su
nset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

c:\users\x\venv\lib\site-packages\onnx_tf\common\__init__.py:87: UserWarning: Fr
ontendHandler.get_outputs_names is deprecated. It will be removed in future rele
ase.. Use node.outputs instead.
  warnings.warn(message)
INFO:root:Start converting onnx pb to tf pb:
Traceback (most recent call last):
  File "E:\Python\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\x\venv\Scripts\onnx-tf.exe\__main__.py", line 9, in <module>
  File "c:\users\x\venv\lib\site-packages\onnx_tf\cli.py", line 19, in main
    return onnx_tf.converter.main(args[1:])
  File "c:\users\x\venv\lib\site-packages\onnx_tf\converter.py", line 23, in mai
n
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "c:\users\x\venv\lib\site-packages\onnx_tf\converter.py", line 173, in co
nvert
    tf_rep = backend.prepare(onnx_model, **kwargs)
  File "c:\users\x\venv\lib\site-packages\onnx_tf\backend.py", line 53, in prepa
re
    super(TensorflowBackend, cls).prepare(model, device, **kwargs)
  File "c:\users\x\venv\lib\site-packages\onnx\backend\base.py", line 74, in pre
pare
    onnx.checker.check_model(model)
  File "c:\users\x\venv\lib\site-packages\onnx\checker.py", line 86, in check_mo
del
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: consume
d_inputs for operator BatchNormalization

==> Context: Bad node spec: input: "conv1" input: "bn_conv1_scale" input: "bn_co
nv1_B" input: "bn_conv1_mean" input: "bn_conv1_var" output: "bn_conv1" name: "bn
_conv1" op_type: "BatchNormalization" attribute { name: "epsilon" f: 0.001 type:
 FLOAT } attribute { name: "is_test" i: 1 type: INT } attribute { name: "consume
d_inputs" ints: 0 ints: 0 ints: 0 ints: 1 ints: 1 type: INTS }`

**Comment by sigrond** [comment]
keras h5 -> tensorflow pb - > android tensorflow
