### ISSUE TITLE
błąd kamery

### ISSUE THREAD

**Issue by sigrond** [Antyradek/pinpolice#3]
Odpaliłem aplikację na moim telefonie, aplikacja natychmiast zdechła i dostałem błąd:

2019-05-18 18:05:23.219 7359-7359/pl.antyradek.pinpolice E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pl.antyradek.pinpolice, PID: 7359
    java.lang.RuntimeException: Camera is being used after Camera.release() was called
        at android.hardware.Camera.setHasPreviewCallback(Native Method)
        at android.hardware.Camera.access$600(Camera.java:150)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1207)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Antyradek** [comment]
Hmm. W „destruktorze” dodałem odłączenie callbacku na ramkę aparatu i chyba działa.
Jak u ciebie także działa, to zamknij problem.

**Comment by sigrond** [comment]
dalej na telefonie aplikacja się wywala, tylko teraz nie widzę tego logu, a właściwie nie dostaję żadnego logu poza połączeniem i rozłączeniem po kliknięciu ok na błędzie

**Comment by sigrond** [comment]
nadal nie wiem co to, nic nie znalazłem w bugreport, ani nie pomogło dodanie `UncaughtExceptionHandler`
